ADD - exit condition

diff --git a/scripts/preinit b/scripts/preinit
--- a/scripts/preinit
+++ b/scripts/preinit
@@ -3,7 +3,7 @@
 if [[ ! -f '.env' ]]; then
     echo "Copying env to .env"
     cp env .env
-    [[ -f '.env.' ]] && echo "Successfully copied" || echo "Failed to copy"
+    [[ -f '.env.' ]] && echo "Successfully copied" || echo "Failed to copy" && exit
 else
-    echo "File .env exists"
+    echo ".env exists"
 fi
